Feat/update endpoints
Telefonica/latch-sdk-python pull request #25
Opened 2024-11-22 10:40 UTC by eozores-telefonica

### :tickets: JIRA ticket
[LATCH-2367](https://jira.tid.es/browse/LATCH-2367)

### :goal_net: What's the goal?
Update access url
Update copyright
Add new endpoints

### :construction: How do we do it?
_Provide a description of the implementation. A list of steps would be ideal._
* Update copyright
* Update urls to latch.tu.com
* Update latch with totps and control-status
* Update project examples, test and added .gitignore

### :blue_book: Documentation changes?
- [x] No docs to update nor create

### :test_tube: How can I test this?
Download project and execute:
``` powershell
    python3 -m venv ./.venv
    .\.venv\Scripts\Activate.ps1
    pip install -r .\requirements.txt
    python3 -m unittest
```

### Last words
- It's a minor upgrade adding new funcionality, should be backward compatible

2024-11-27 11:33 UTC, alfred82santa requested changes

2024-11-27 11:33 UTC, alfred82santa commented on examples/example_sdk_latch_totp.py
> +ACCOUNT_ID = "CBrYKXiFwwK2BwzPUinwmhT4LWZE4BAnbeVYupdpB4gBLxzzimtzbt33HC926JXj"
se te ha colado

2024-11-27 11:36 UTC, alfred82santa requested changes

2024-11-27 11:36 UTC, alfred82santa commented on examples/example_sdk_latch_pairing.py
> +        logging.info(f"Status: {response.data}")
Process response data. Don't print a json. It must print "your latch is lock and you can not be allowed to perform action" or "your latch is open and you are able to perform action"

2024-11-28 15:40 UTC, eozores-telefonica commented on examples/example_sdk_latch_pairing.py
> +        logging.info(f"Status: {response.data}")
Done, thx for the feedback

2024-12-12 17:56 UTC, alfred82santa requested changes

2024-12-12 17:56 UTC, alfred82santa commented on examples/example_sdk_latch_basic.py
> +            logging.info(f"Your latch is lock and you can not be allowed to perform action")
```suggestion
            logging.info(f"Your latch is locked and you are not allowed to perform action")
```

2024-12-12 18:07 UTC, alfred82santa approved these changes

2025-08-11 10:19 UTC, merged